### ISSUE TITLE
Add sonarjs as eslint plugin

### ISSUE THREAD

**Issue by kyrcha** [cyclopt/jssa#6]
https://github.com/SonarSource/eslint-plugin-sonarjs

**Comment by MichaelPap** [comment]
Added in commit 3b074932f3012e171861553af3717fb3cfebe9a8. 
eslint-plugin-sonarjs current version is 0.2.0.
Did not remove sonarjs due to the fact that eslint-plugin-sonarjs does not yet include all the sonarjs rules.
